import type { NextPage } from "next";
import { Link } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";

import { Data } from "./api/hello";
import { useEffect, useState } from "react";

const Home: NextPage<Data> = (data) => {

  const [ dataSource, setDataSource ] = useState<Data | null>(null);

  useEffect(()=>{
    const getData = async () => {
      const res = await fetch("api/hello");
      const data = await res.json();
      setDataSource(data);
    };
    getData();
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <h1 className="text-3xl font-bold underline text-blue-500">
          Hello world!
        </h1>
        <hr />
        <Link href="/about" color="blue.400" _hover={{ color: "blue.500" }}>
          About {dataSource?.name}
        </Link>

        <footer>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </footer>
      </div>
    </>
  );
};

export default Home;
