import type { NextPage } from "next";
import { Link } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <h1 className="text-3xl font-bold underline text-blue-500">
          Hello world!
        </h1>
        <hr />
        <Link href="/about" color="blue.400" _hover={{ color: "blue.500" }}>
          About
        </Link>

        <footer>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </footer>
      </div>
    </>
  );
};

export default Home;
